# Quitar 'version' si Docker Compose da warning, aunque no es un error funcional.
# version: '3.8' 

services:
  storage: 
    image: mongo:6.0
    container_name: mongo-storage
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s   # CORREGIDO
      retries: 5    # CORREGIDO
    networks:
      - distribuidos_network

  cache_entrega1: # Tu servicio de caché original de la Entrega 1 (Flask app)
    build: ./cache
    container_name: cache_entrega1_service 
    depends_on:
      storage:
        condition: service_healthy
    ports:
      - "5001:5001" 
    environment:
      - CACHE_SIZE=8
      - POLICY=LRU
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/metrics"]
      interval: 15s
      timeout: 10s  # CORREGIDO
      retries: 10   # CORREGIDO
    networks:
      - distribuidos_network

  redis_actual_cache: # Nuevo servicio Redis real
    image: redis:alpine 
    container_name: redis_cache_for_pig_results
    ports:
      - "6380:6379" 
    volumes:
      - redis_pig_data:/data 
    healthcheck: 
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s   # CORREGIDO
      retries: 5    # CORREGIDO
    networks:
      - distribuidos_network

  scraper:
    build: ./scraper
    container_name: scraper 
    depends_on:
      storage: 
        condition: service_healthy
    environment: 
      - MONGO_HOST=storage
      - MONGO_PORT=27017
      - DB_NAME_SCRAPER=waze_db
      - COLLECTION_NAME_SCRAPER=eventos
      - SCRAPE_INTERVAL_SECONDS=300 
      - MAX_EVENTS_TO_COLLECT=450
    volumes:
      - ./scraper:/app
    networks:
      - distribuidos_network

  mongo_exporter:
    build: 
      context: ./mongo_exporter
      dockerfile: Dockerfile
    container_name: mongo_exporter_service
    depends_on:
      storage: 
        condition: service_healthy
      scraper: 
        condition: service_completed_successfully
    environment:
      - MONGO_HOST_EXPORTER=storage
      - DB_NAME_EXPORTER=waze_db
      - COLLECTION_NAME_EXPORTER=eventos
      - OUTPUT_TSV_PATH_EXPORTER=/exported_data/waze_events.tsv 
    volumes:
      - ./entrega2/pig_processing/data_input:/exported_data 
    networks:
      - distribuidos_network

  pig_processor:
    build: 
      context: ./entrega2/pig_processing
      dockerfile: Dockerfile.pig 
    container_name: pig_service_container
    volumes:
      - ./entrega2/pig_processing/scripts:/pig_scripts
      - ./entrega2/pig_processing/data_input:/pig_input_data 
      - ./entrega2/pig_processing/data_output:/pig_output_data 
    command: ["pig", "-x", "local", "-f", "/pig_scripts/process_waze_data.pig"]
    networks:
      - distribuidos_network
    depends_on:
      mongo_exporter: 
        condition: service_completed_successfully

  cache_loader:
    build: 
      context: ./cache_loader
      dockerfile: Dockerfile
    container_name: cache_loader_service
    depends_on:
      pig_processor: 
        condition: service_completed_successfully
      redis_actual_cache: # Depende del NUEVO servicio Redis
        condition: service_healthy
    environment:
      - REDIS_HOST_LOADER=redis_actual_cache # Apunta al NUEVO servicio Redis
      - REDIS_PORT_LOADER=6379     
      - PIG_OUTPUT_BASE_DIR=/pig_results_input
    volumes:
      - ./entrega2/pig_processing/data_output:/pig_results_input 
    networks:
      - distribuidos_network

volumes:
  mongo_data:
  redis_pig_data:

networks:
  distribuidos_network: 
    driver: bridge