version: '3.8'
services:
  storage:
    build: ./storage
    container_name: mongo-storage
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  scraper:
    build: ./scraper
    depends_on:
      - storage
    container_name: scraper
    volumes:
      - ./scraper:/app

volumes:
  mongo_data:
