version: '3.8'

services:
  storage:
    build: ./storage
    container_name: mongo-storage
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  scraper:
    build: ./scraper
    depends_on:
      - storage
    container_name: scraper
    volumes:
      - ./scraper:/app
  cleaner:
    build: ./storage
    container_name: cleaner
    depends_on:
      - storage
    command: python cleaner.py

  cache:
    build: ./cache
    depends_on:
      - storage
    container_name: cache
    ports:
      - "5001:5001"

  traffic_generator:
    build: ./traffic_generator
    depends_on:
      - cache
    container_name: traffic_generator

volumes:
  mongo_data:
