services:
  storage:
    image: mongo:6.0
    container_name: mongo-storage
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  scraper:
    build: ./scraper
    container_name: scraper
    depends_on:
      - storage
    volumes:
      - ./scraper:/app

  traffic_generator:
    build: ./traffic_generator
    container_name: traffic-generator
    depends_on:
      - storage

  cache:
    build: ./cache
    container_name: cache
    depends_on:
      - traffic_generator

  cleaner:
    build: ./storage
    container_name: cleaner
    depends_on:
      - storage
    command: python cleaner.py

volumes:
  mongo_data:
