version: '3.8'
services:
  scraper:
    build: ./scraper
    volumes:
      - ./scraper:/app
    command: ["sleep", "infinity"]

  storage:
    build: ./storage
    volumes:
      - ./storage:/app
    command: ["sleep", "infinity"]

  traffic_generator:
    build: ./traffic_generator
    volumes:
      - ./traffic_generator:/app
    command: ["sleep", "infinity"]

  cache:
    build: ./cache
    volumes:
      - ./cache:/app
    command: ["sleep", "infinity"]
