version: '3.8' # Puedes quitar esta línea

services:
  storage: 
    image: mongo:6.0
    container_name: mongo-storage
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - distribuidos_network

  scraper:
    build: ./scraper
    container_name: scraper 
    depends_on:
      storage:
        condition: service_healthy
    environment: 
      - MONGO_HOST=storage 
      - MONGO_PORT=27017
      - DB_NAME_SCRAPER=waze_db
      - COLLECTION_NAME_SCRAPER=eventos
      - SCRAPE_INTERVAL_SECONDS=300 
      - MAX_EVENTS_TO_COLLECT=250
    volumes:
      - ./scraper:/app
    networks:
      - distribuidos_network

  pig_processor:
    build:
      context: ./entrega2/pig_processing  # El contexto es la carpeta que contiene Dockerfile.pig
      dockerfile: Dockerfile.pig          # <--- CAMBIO AQUÍ: Nombre correcto del Dockerfile
    container_name: pig_service_container
    volumes:
      - ./entrega2/pig_processing/scripts:/pig_scripts
      - ./entrega2/pig_processing/data_input:/pig_input_data
      - ./entrega2/pig_processing/data_output:/pig_output_data
    command: ["pig", "-f", "/pig_scripts/test_load_store.pig"]
    networks:
      - distribuidos_network
    # depends_on: 
    #   storage:
    #     condition: service_healthy

volumes:
  mongo_data:

networks:
  distribuidos_network:
    driver: bridge