version: '3.8'
services:
  storage:
    image: mongo:6.0
    container_name: mongo-storage
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  cache:
    build: ./cache
    container_name: cache
    depends_on:
      - storage
    ports:
      - "5001:5001"
    environment:
      - CACHE_SIZE=1
      - POLICY=LRU

  traffic_generator:
    build: ./traffic_generator
    container_name: traffic_generator
    depends_on:
      - cache
    environment:
      - MODE=empirical        # Cambiar a "poisson", "uniform", etc. según se necesite
      - RATE=2.0
    

  scraper:
    build: ./scraper
    container_name: scraper
    depends_on:
      - storage
    volumes:
      - ./scraper:/app

  cleaner:
    build: ./storage
    container_name: cleaner
    depends_on:
      - storage
    command: python cleaner.py

volumes:
  mongo_data:
